### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by Mannuel25**

### CODE REVIEW

**Comment by zadilkhwaja** [comment]
Very nice @Mannuel25 thank you!

**Comment by Mannuel25** [comment]
You're welcome. I look forward to collaborating with you on more projects. I'm of the opinion that we work on something similar to this, or a bit complex for hacktoberfest.. you've any ideas of something we can get our hands on?

**Comment by zadilkhwaja** [comment]
Actually I've never participated in hactoberfest before so I'm not sure. If we collaborate do we have to submit 4 or 8 PRs? Not sure what ideas you're asking for but I'm ok working with Python, Django etc.

**Comment by Mannuel25** [comment]
Okay, no issues. If i come up with any ideas, I'll do well to hit you up!

**Pull request merged**
